[package]
name = "r5d3"
version = "0.1.0"
edition = "2021"
authors = ["LOU Xun <xun.lou@controlant.com>"]
description = "DNS automation for multi-account Route53 setup"

[dependencies]
anyhow = "1"
argh = "0.1"

# AWS
aws-types = "0.53"
aws-config = "0.52"
aws-sdk-route53 = "0.22"
aws-sdk-acm = "0.22"

# Runtime
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

# Tracing
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.11", features = ["grpc-tonic"] }
tracing-opentelemetry = "0.18"
