[package]
name = "r5d3"
version = "0.2.3"
edition = "2021"
authors = ["LOU Xun <xun.lou@controlant.com>"]
description = "DNS automation for multi-account Route53 setup"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }

# AWS
aws-types = "0.56"
aws-config = "0.56"
aws-sdk-route53 = "0.30"
aws-sdk-acm = "0.30"
aws-sdk-organizations = "0.30"
aws-sdk-sts = "0.30"

# Runtime
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

# Tracing
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
opentelemetry = { version = "0.20", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.13", features = ["grpc-tonic"] }
tracing-opentelemetry = "0.21"
