[package]
name = "r5d3"
version = "0.2.4"
edition = "2021"
authors = ["LOU Xun <xun.lou@controlant.com>"]
description = "DNS automation for multi-account Route53 setup"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
fastrand = "2"

# AWS
control-aws = { git = "https://github.com/controlant-org/control-aws.git", rev = "326b086" }
aws-types = "0.57"
aws-config = "0.57"
aws-sdk-route53 = "0.36"
aws-sdk-acm = "0.36"
aws-sdk-sts = "0.37"

# Runtime
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

# Tracing
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
opentelemetry = "0.21"
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.14", features = ["grpc-tonic"] }
tracing-opentelemetry = "0.22"
