[package]
name = "r5d3"
version = "0.1.0"
edition = "2021"
authors = ["LOU Xun <xun.lou@controlant.com>"]
description = "DNS promoter"

[dependencies]
anyhow = "1"
argh = "0.1"

# AWS
aws-types = "0.51"
aws-config = "0.49"
aws-sdk-route53 = "0.19"
aws-sdk-acm = "0.19"

# Runtime
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

# Tracing
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = "0.3"
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.11", features = ["grpc-tonic"] }
tracing-opentelemetry = "0.18"
